lots more major changes

diff --git a/functions/_mf_define b/functions/_mf_define
--- a/functions/_mf_define
+++ b/functions/_mf_define
@@ -3,9 +3,10 @@ local editor="${EDITOR##*/}"
     local ftopts="-c \"set ft=zsh\"" ||
 [[ $editor == micro ]] &&
     local ftopts="-filetype=zsh"
-$EDITOR "$ftopts" "${MFUNCDIR}/$i" || {
-    echo "aborting..."
-    return
-}
-echo "new function '$i' created in $MFUNCDIR"
-autoload $i
+$EDITOR "$ftopts" "${MFUNCDIR}/$i"  &&
+    [[ -f "${MFUNCDIR}/$i" ]] &&
+        autoload $i || {
+            echo "aborting..."
+            return 1
+        }
+$edit || echo "new function '$i' created in $MFUNCDIR"
