make use of $EDITOR instead of redirecting stdin + more fixes and improvements

diff --git a/functions/mfunc b/functions/mfunc
--- a/functions/mfunc
+++ b/functions/mfunc
@@ -8,10 +8,12 @@
 for i; do
     # TODO: input sanitization
     [[ -e $MFUNCDIR/$i ]] && {
-        _mf_yesorno "function $i already exists, overwrite? (Y/n)" || {
-            echo "aborted"
+        read -q "choice?function $i already exists, press Y/y to edit with $EDITOR or any other key to abort: " || {
+            echo
+            echo "aborting..."
             return
         }
+        echo
         unfunction $i   # forget the old version first
     }
     _mf_define $i
